apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm-frontend-deployment
  labels:
    app: idm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idm-frontend-selector
  template:
    metadata:
      labels:
        app: idm-frontend-selector
    spec:
      containers:
        - name: idm-frontend
          image: de.icr.io/idm-registry/idm-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: keycloak-config
            - configMapRef:
                name: database-config
            - configMapRef:
                name: frontend-config
      imagePullSecrets:
        - name: default-de-icr-io
