kind: Service
apiVersion: v1
metadata:
  name: idm-frontend-service
  namespace: default
  labels:
    app: idm-frontend-selector
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3030
  selector:
    app: idm-frontend-selector
  type: LoadBalancer
